services:
  memcachedadmin:
    container_name: 'memcachedadmin'
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
      target: php-dev
      args:
        - BUILDKIT_INLINE_CACHE=1
    tty: true
    ports:
      - '8080:80'
    restart: unless-stopped
    volumes:
      - './app/:/app/'
    environment:
      - 'TZ=UTC'
      - 'SERVER=memcached:11211'
    networks:
      - network1

  memcached:
    container_name: 'memcached'
    image: 'memcached:1.6'
    tty: true
    restart: unless-stopped
    environment:
      - 'TZ=UTC'
    networks:
      - network1

networks:
  network1:
    driver: bridge
